default: &default
  adapter: postgresql
  username: pguser
  password: pguser
  host: localhost
  port: 5432
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: authy_development

test:
  <<: *default
  database: authy_test

production:
  <<: *default
  database: authy_production
